version: '3'

services: 
  nginx: 
    image: nginx:latest 
    restart: unless-stopped
    tty: true
    ports: 
      -  "80:80" 
    volumes: 
      - ./config/nginx/nginx.app.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/html
    networks:
      - dockerdb_default
    links:
      - app

  app: 
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: redmindte
    restart: unless-stopped
    tty: true
    environment: 
      build: "dev"
    expose: 
      - "9000"
    env_file:
      - ./config/env_params
    volumes:
      - ./src:/var/www/html
    networks:
      - dockerdb_default

#Docker Networks
networks:
  dockerdb_default:
    external: true
