FROM php:8.2-fpm-buster

LABEL maintainer="Carlos Guajardo cguajardo@redmin.cl"

# Copy the script from your host machine to the Docker image
COPY config/dependency_installer.sh /dependency_installer.sh

# Give execution permissions
RUN chmod +x /dependency_installer.sh

# Execute the script
RUN /dependency_installer.sh

# Set the working directory to /app
WORKDIR /var/www/html

#PHP
COPY --chmod=777 config/php/php8/php-fpm.conf /etc/php8/php-fpm.conf
COPY --chmod=777 config/php/php8/www.conf /etc/php8/php-fpm.d/www.conf
COPY --chmod=777 config/php/php8/php.ini /etc/php8/php.ini

# Installing composer
COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

EXPOSE 9000

CMD ["php-fpm"]