version: '3'

services: 
  nginx: 
    image: nginx:latest 
    restart: unless-stopped
    tty: true
    ports: 
      -  "80:80" 
      -  "443:443" 
    volumes: 
      - ./config/nginx/nginx.app.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/ssl/cert.crt:/etc/ssl/private/cert.crt
      - ./config/ssl/cert.key:/etc/ssl/private/cert.key
    networks:
      - app-network
    links:
      - app

  app: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    env_file:
      - ./config/env_params
    volumes:
      - ./app_storage/:/var/www/html/storage/
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge