version: '3'

services: 
  app: 
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: redmindte
    restart: unless-stopped
    tty: true
    environment: 
      build: "dev"
    ports: 
      - "8080:80"
    env_file:
      - ./config/env_params
    volumes:
      - ./src:/var/www/html
    networks:
      - dockerdb_dockerdb

#Docker Networks
networks:
  dockerdb_dockerdb:
    external: true
