FROM php:8.2-fpm-alpine3.16

Maintainer Carlos Guajardo cguajardo@redmin.cl

RUN apk update && apk upgrade

RUN echo "UTC" >/etc/timezone
ENV ALPINE_MIRROR "http://dl-cdn.alpinelinux.org/alpine"

RUN echo "${ALPINE_MIRROR}/latest-stable/main" >>/etc/apk/repositories
RUN apk add --no-cache nodejs-current --repository="${ALPINE_MIRROR}/latest-stable/community"

# Essentials
RUN apk add --no-cache zip
RUN apk add --no-cache unzip
RUN apk add --no-cache curl
RUN apk add --no-cache sqlite
RUN apk add --no-cache nginx
RUN apk add --no-cache supervisor
RUN apk add --no-cache chromium chromium-chromedriver
RUN apk add nginx-mod-http-headers-more
RUN apk add --no-cache npm
# Installing bash
RUN apk add --no-cache bash
RUN apk add --no-cache npm
RUN apk add --no-cache yarn
RUN apk add --no-cache py3-pip

RUN python -m pip install rich

# Set the working directory to /app
WORKDIR /var/www/html

RUN docker-php-ext-install pdo pdo_mysql
RUN docker-php-ext-enable pdo pdo_mysql

RUN apk add --no-cache php-soap
RUN apk add --no-cache php-xml

# RUN set -eux
RUN apk update
RUN apk add libxml2-dev
RUN apk add php8-soap

RUN apk add --no-cache postgresql-dev
RUN docker-php-ext-install soap
RUN docker-php-ext-enable soap

RUN apk add --no-cache gd libpng-dev libjpeg-turbo-dev libwebp-dev freetype-dev php-bcmath
RUN docker-php-ext-install bcmath
RUN docker-php-ext-enable bcmath

RUN docker-php-ext-configure gd --enable-gd --with-freetype --with-jpeg --with-webp
RUN docker-php-ext-install gd

# Configure supervisor
RUN mkdir -p /etc/supervisor.d/
COPY config/supervisord.ini /etc/supervisor.d/supervisord.ini

#PHP
COPY config/php/php8/php-fpm.conf /etc/php8/php-fpm.conf
COPY config/php/php8/www.conf /etc/php8/php-fpm.d/www.conf
COPY config/php/php8/php.ini /etc/php8/php.ini

#Nginx
COPY config/nginx/nginx.dev.conf /etc/nginx/nginx.conf
COPY config/nginx/server.dev.conf /etc/nginx/conf.d/3sod.conf
RUN mkdir -p /run/nginx/
RUN touch /run/nginx/nginx.pid
RUN ln -sf /dev/stdout /var/log/nginx/access.log
RUN ln -sf /dev/stderr /var/log/nginx/error.log

# Installing composer
COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

# Install dependencies
RUN composer install

EXPOSE 80 9000

CMD ["python", "./init.py"]
CMD ["supervisord", "-c", "/etc/supervisor.d/supervisord.ini"]
